"""Evaluation script with LLM-as-a-judge for TelecomPlus support agent.

This script evaluates the agent's responses using Gemini as a judge.
It calculates multiple metrics: accuracy, completeness, relevance.
"""

import json
from datetime import datetime
import time  # ADD THIS
import pandas as pd
import google.generativeai as genai

from src.config import GOOGLE_API_KEY, LLM_MODEL
from src.main import answer

# Configure Gemini
genai.configure(api_key=GOOGLE_API_KEY)


def evaluate_response_with_llm(question: str, expected_answer: str, 
                                agent_answer: str) -> dict:
    """Evaluate agent response using Gemini as a judge.
    
    This implements LLM-as-a-judge methodology to score responses on:
    - Factual accuracy (0-4 points)
    - Completeness (0-3 points)
    - Relevance (0-3 points)
    Total: 0-10 points
    
    Args:
        question: The customer question
        expected_answer: The expected answer from the dataset
        agent_answer: The answer generated by your agent
        
    Returns:
        Dictionary with score and detailed evaluation
    """
    model = genai.GenerativeModel(LLM_MODEL)
    
    prompt = f"""Tu es un évaluateur expert pour un système de support client téléphonique.
Évalue la réponse de l'agent par rapport à la réponse attendue.

Question du client:
{question}

Réponse attendue:
{expected_answer}

Réponse de l'agent:
{agent_answer}

Évalue selon ces critères:

1. EXACTITUDE FACTUELLE (0-4 points):
   - 4: Toutes les informations sont correctes et précises
   - 3: Informations majoritairement correctes avec erreurs mineures
   - 2: Quelques informations correctes mais erreurs significatives
   - 1: La plupart des informations sont incorrectes
   - 0: Complètement faux ou hors sujet

2. COMPLÉTUDE (0-3 points):
   - 3: Répond complètement à tous les aspects de la question
   - 2: Répond aux aspects principaux mais manque des détails
   - 1: Répond partiellement, manque des éléments importants
   - 0: Ne répond pas vraiment à la question

3. PERTINENCE (0-3 points):
   - 3: Directement pertinent, sans informations superflues
   - 2: Pertinent mais contient des éléments non nécessaires
   - 1: Partiellement pertinent avec beaucoup d'informations inutiles
   - 0: Hors sujet

Réponds UNIQUEMENT avec un JSON (pas de markdown, pas de texte avant/après):
{{
    "factual_accuracy": <score 0-4>,
    "completeness": <score 0-3>,
    "relevance": <score 0-3>,
    "total_score": <somme des 3 scores, sur 10>,
    "explanation": "Explication courte de l'évaluation (2-3 phrases)",
    "main_issues": ["problème 1", "problème 2"] ou [] si aucun problème
}}"""

    try:
        response = model.generate_content(prompt)
        response_text = response.text.strip()
        
        # Clean markdown if present
        if response_text.startswith("```"):
            lines = response_text.split("\n")
            response_text = "\n".join(lines[1:-1])
            if response_text.startswith("json"):
                response_text = response_text[4:].strip()
        
        # Remove any remaining backticks
        response_text = response_text.replace("```", "").strip()
        
        evaluation = json.loads(response_text)
        
        # Validate and cap scores
        evaluation["factual_accuracy"] = max(0, min(4, evaluation.get("factual_accuracy", 0)))
        evaluation["completeness"] = max(0, min(3, evaluation.get("completeness", 0)))
        evaluation["relevance"] = max(0, min(3, evaluation.get("relevance", 0)))
        evaluation["total_score"] = (
            evaluation["factual_accuracy"] + 
            evaluation["completeness"] + 
            evaluation["relevance"]
        )
        
        return evaluation
        
    except Exception as e:
        print(f"[ERROR] LLM evaluation failed: {e}")
        # Fallback: simple keyword matching
        return fallback_evaluation(expected_answer, agent_answer)


def fallback_evaluation(expected_answer: str, agent_answer: str) -> dict:
    """Fallback evaluation if LLM fails.
    
    Simple keyword-based scoring as backup.
    """
    import re
    
    expected_lower = expected_answer.lower()
    agent_lower = agent_answer.lower()
    
    # Extract key words (nouns, numbers)
    expected_words = set(re.findall(r'\b\w{4,}\b', expected_lower))
    agent_words = set(re.findall(r'\b\w{4,}\b', agent_lower))
    
    # Calculate overlap
    if len(expected_words) == 0:
        overlap = 0.5
    else:
        overlap = len(expected_words & agent_words) / len(expected_words)
    
    score = int(overlap * 10)
    
    return {
        "factual_accuracy": int(overlap * 4),
        "completeness": int(overlap * 3),
        "relevance": int(overlap * 3),
        "total_score": score,
        "explanation": f"Évaluation automatique de secours (overlap: {overlap:.2%})",
        "main_issues": ["Évaluation LLM a échoué, score basique utilisé"]
    }


def calculate_statistics(results: list) -> dict:
    """Calculate aggregate statistics from evaluation results.
    
    Args:
        results: List of evaluation result dictionaries
        
    Returns:
        Dictionary with statistics
    """
    if not results:
        return {}
    
    df = pd.DataFrame(results)
    
    stats = {
        "total_questions": len(df),
        "mean_score": float(df["total_score"].mean()),
        "median_score": float(df["total_score"].median()),
        "std_score": float(df["total_score"].std()),
        "min_score": int(df["total_score"].min()),
        "max_score": int(df["total_score"].max()),
        "mean_factual_accuracy": float(df["factual_accuracy"].mean()),
        "mean_completeness": float(df["completeness"].mean()),
        "mean_relevance": float(df["relevance"].mean()),
        "pass_rate": float((df["total_score"] >= 6).sum() / len(df) * 100),  # 60% threshold
    }
    
    # Per difficulty stats
    if "difficulty" in df.columns:
        difficulty_stats = df.groupby("difficulty")["total_score"].agg([
            "count", "mean", "min", "max"
        ]).to_dict()
        stats["by_difficulty"] = difficulty_stats
    
    return stats


def run_evaluation():
    """Run complete evaluation on all questions from the evaluation dataset."""
    
    print("=" * 80)
    print("TELECOMPLUS AGENT EVALUATION - LLM-as-a-Judge")
    print("=" * 80)
    print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    
    # Load evaluation questions
    print("Loading evaluation questions...")
    try:
        df = pd.read_excel("data/evaluation_questions.xlsx")
    except FileNotFoundError:
        print("ERROR: data/evaluation_questions.xlsx not found!")
        print("Make sure you're running this from the project root directory.")
        return
    
    print(f"Loaded {len(df)} questions\n")
    print("=" * 80)
    
    results = []
    
    # Evaluate each question
    for idx, row in df.iterrows():
        question = row["Question"]
        expected_answer = row["Réponse Attendue"]
        difficulty = row.get("Difficulté", "Unknown")
        
        print(f"\n[{idx + 1}/{len(df)}] Difficulty: {difficulty}")
        print(f"Q: {question}")
        
        # Get agent's answer
        try:
            agent_answer = answer(question)
            # Truncate for display
            display_answer = agent_answer[:200] + "..." if len(agent_answer) > 200 else agent_answer
            print(f"A: {display_answer}")
        except Exception as e:
            agent_answer = f"ERROR: {str(e)}"
            print(f"A: {agent_answer}")
        
        # WAIT to avoid rate limits (5 requests/minute = 12 seconds between requests)
        print("Waiting 15 seconds to avoid rate limits...")
        time.sleep(15)
        
        # Evaluate with LLM
        print("Evaluating with LLM judge...")
        evaluation = evaluate_response_with_llm(question, expected_answer, agent_answer)
        
        print(f"Score: {evaluation['total_score']}/10 "
              f"(Accuracy: {evaluation['factual_accuracy']}/4, "
              f"Completeness: {evaluation['completeness']}/3, "
              f"Relevance: {evaluation['relevance']}/3)")
        
        if evaluation.get("explanation"):
            print(f"Explanation: {evaluation['explanation']}")
        
        if evaluation.get("main_issues"):
            print(f"Issues: {', '.join(evaluation['main_issues'])}")
        
        # Store results
        results.append({
            "question_id": idx + 1,
            "question": question,
            "expected_answer": expected_answer,
            "agent_answer": agent_answer,
            "difficulty": difficulty,
            "total_score": evaluation["total_score"],
            "factual_accuracy": evaluation["factual_accuracy"],
            "completeness": evaluation["completeness"],
            "relevance": evaluation["relevance"],
            "explanation": evaluation["explanation"],
            "main_issues": ", ".join(evaluation.get("main_issues", []))
        })
        
        print("-" * 80)
    
    # Calculate final statistics
    print("\n" + "=" * 80)
    print("FINAL EVALUATION RESULTS")
    print("=" * 80)
    
    stats = calculate_statistics(results)
    
    print(f"\nTotal questions evaluated: {stats['total_questions']}")
    print(f"\nScore Statistics (out of 10):")
    print(f"  Mean:   {stats['mean_score']:.2f}")
    print(f"  Median: {stats['median_score']:.2f}")
    print(f"  Std:    {stats['std_score']:.2f}")
    print(f"  Min:    {stats['min_score']:.0f}")
    print(f"  Max:    {stats['max_score']:.0f}")
    
    print(f"\nComponent Scores (averages):")
    print(f"  Factual Accuracy: {stats['mean_factual_accuracy']:.2f}/4")
    print(f"  Completeness:     {stats['mean_completeness']:.2f}/3")
    print(f"  Relevance:        {stats['mean_relevance']:.2f}/3")
    
    print(f"\nPass Rate (≥6/10): {stats['pass_rate']:.1f}%")
    
    # Save detailed results
    results_df = pd.DataFrame(results)
    output_file = f"evaluation_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    results_df.to_excel(output_file, index=False)
    print(f"\n✓ Detailed results saved to: {output_file}")
    
    # Save summary statistics
    stats_file = f"evaluation_stats_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(stats_file, 'w', encoding='utf-8') as f:
        json.dump(stats, f, indent=2, ensure_ascii=False)
    print(f"✓ Statistics saved to: {stats_file}")
    
    print("\n" + "=" * 80)
    print(f"Evaluation completed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 80)


if __name__ == "__main__":
    run_evaluation()