"""Intelligent data queries using LLM to generate pandas operations.

This module uses Gemini to understand questions and query Excel data appropriately.
"""

import json
from typing import Dict, Any, List
import pandas as pd
import google.generativeai as genai

from src.config import GOOGLE_API_KEY, LLM_MODEL

# Configure Gemini
genai.configure(api_key=GOOGLE_API_KEY)


def get_dataframe_info(dfs: Dict[str, pd.DataFrame], table_names: List[str]) -> str:
    """Get schema information for specified tables.
    
    Args:
        dfs: Dictionary of all dataframes
        table_names: List of table names to describe
        
    Returns:
        String description of table schemas
    """
    info_parts = []
    
    for table_name in table_names:
        if table_name in dfs:
            df = dfs[table_name]
            info_parts.append(f"Table '{table_name}':")
            info_parts.append(f"  Colonnes: {list(df.columns)}")
            info_parts.append(f"  Nombre de lignes: {len(df)}")
            info_parts.append(f"  Exemple de données:\n{df.head(2).to_string()}")
            info_parts.append("")
    
    return "\n".join(info_parts)


def query_excel_intelligent(question: str, dfs: Dict[str, pd.DataFrame], 
                            relevant_tables: List[str]) -> Any:
    """Use LLM to understand the question and query data intelligently.
    
    Args:
        question: User's question
        dfs: Dictionary of all dataframes {table_name: dataframe}
        relevant_tables: List of tables identified as relevant
        
    Returns:
        Query results (dict, list, or descriptive string)
    """
    if not relevant_tables:
        return "Aucune table de données n'a été identifiée comme pertinente."
    
    # Get schema info for relevant tables
    schema_info = get_dataframe_info(dfs, relevant_tables)
    
    model = genai.GenerativeModel(LLM_MODEL)
    
    prompt = f"""Tu es un expert en analyse de données pour TelecomPlus.
Analyse la question et détermine comment interroger les données.

Question: {question}

Tables disponibles:
{schema_info}

Tâche: Décris EXACTEMENT comment filtrer/analyser les données pour répondre à cette question.

Réponds avec un JSON (pas de markdown, pas de backticks):
{{
    "action": "filter" ou "aggregate" ou "direct",
    "table": "nom_de_la_table_principale",
    "description": "description de ce qu'il faut faire",
    "filters": {{"colonne": "valeur"}} si filtrage nécessaire (sinon {{}}),
    "columns": ["col1", "col2"] colonnes à retourner (ou [] pour toutes)
}}

Exemples:
- Pour "combien de clients": {{"action": "aggregate", "table": "clients", "filters": {{}}, "columns": []}}
- Pour "forfaits disponibles": {{"action": "direct", "table": "forfaits", "filters": {{}}, "columns": []}}
"""

    try:
        response = model.generate_content(prompt)
        response_text = response.text.strip()
        
        # Clean markdown if present
        if response_text.startswith("```"):
            lines = response_text.split("\n")
            response_text = "\n".join(lines[1:-1])
            if response_text.startswith("json"):
                response_text = response_text[4:].strip()
        
        # Remove any remaining backticks
        response_text = response_text.replace("```", "").strip()
        
        query_plan = json.loads(response_text)
        
        # Execute the query plan
        result = execute_query_plan(query_plan, dfs)
        return result
        
    except Exception as e:
        print(f"[ERROR] Intelligent query failed: {e}")
        return fallback_query(question, dfs, relevant_tables)


def execute_query_plan(plan: Dict[str, Any], dfs: Dict[str, pd.DataFrame]) -> Any:
    """Execute the query plan generated by LLM.
    
    Args:
        plan: Query plan from LLM
        dfs: Dictionary of dataframes
        
    Returns:
        Query results
    """
    table_name = plan.get("table")
    if not table_name or table_name not in dfs:
        return f"Table '{table_name}' non trouvée."
    
    df = dfs[table_name]
    action = plan.get("action", "direct")
    
    try:
        if action == "aggregate":
            # Return summary statistics
            return {
                "table": table_name,
                "total_rows": len(df),
                "columns": list(df.columns),
                "sample": df.head(5).to_dict('records')
            }
        
        elif action == "filter":
            filters = plan.get("filters", {})
            filtered_df = df.copy()
            
            # Apply filters
            for col, value in filters.items():
                if col in filtered_df.columns:
                    filtered_df = filtered_df[filtered_df[col] == value]
            
            # Select columns
            columns = plan.get("columns", [])
            if columns:
                result_df = filtered_df[columns]
            else:
                result_df = filtered_df
            
            return {
                "table": table_name,
                "rows_found": len(result_df),
                "data": result_df.head(10).to_dict('records')
            }
        
        elif action == "direct":
            # Return data directly
            columns = plan.get("columns", [])
            if columns:
                result_df = df[columns]
            else:
                result_df = df
            
            return {
                "table": table_name,
                "total_rows": len(result_df),
                "data": result_df.head(10).to_dict('records')
            }
        
        else:
            # Unknown action, return sample
            return {
                "table": table_name,
                "note": "Action inconnue, retour de données de base",
                "data": df.head(5).to_dict('records')
            }
            
    except Exception as e:
        print(f"[ERROR] Query execution failed: {e}")
        return {
            "error": str(e), 
            "plan": plan,
            "table": table_name,
            "sample": df.head(3).to_dict('records') if table_name in dfs else None
        }


def fallback_query(question: str, dfs: Dict[str, pd.DataFrame], 
                   relevant_tables: List[str]) -> Any:
    """Fallback query using simple keyword matching.
    
    Args:
        question: User's question
        dfs: Dictionary of dataframes
        relevant_tables: Tables to search
        
    Returns:
        Basic query results
    """
    print("[DATA] Using fallback query method")
    
    # Try each relevant table
    for table_name in relevant_tables:
        if table_name in dfs:
            df = dfs[table_name]
            
            # Return summary for the first relevant table found
            return {
                "table": table_name,
                "total_rows": len(df),
                "columns": list(df.columns),
                "sample_data": df.head(5).to_dict('records'),
                "note": "Requête basique (fallback)"
            }
    
    return "Aucune donnée trouvée pour cette question."


# Test
if __name__ == "__main__":
    from load_data import load_dataframes
    
    print("Testing data queries...")
    
    dfs = load_dataframes()
    
    if dfs:
        test_question = "Combien de clients avez-vous?"
        print(f"\nTest question: {test_question}")
        
        result = query_excel_intelligent(test_question, dfs, ["clients"])
        print(f"\nResult:")
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print("No dataframes loaded!")